### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kritixilithos** [kritixilithos/Carrot#1]
### Language/Interpreter Features

(in no particular order)

- [ ] `%` modulo operator
- [ ] variable precision numbers (like in python)
- [ ] math builtins (pi, e, complex numbers and the lot)
- [ ] registers (like vim)
- [ ] `_` for negative sign for numbers
- [x] add tests

### Site

- [ ] update the Carrot website with the new interpreter

**Comment by kritixilithos** [comment]
Suggestion: redo the interpreter

Separate the functions of the lexer, parser and the interpreter.  Using ASTs will allow nested expressions and can make Carrot Turing Complete. Until then, this list will freeze. As of now, I'm thinking about creating an interpreter in node as well.

Edit:

[status:completed]

**Comment by kritixilithos** [comment]
[status:completed]

**Comment by somebody1234** [comment]
For arbitrary precision, you can use any of the various libraries. (I've used [this one](https://github.com/MikeMcl/bignumber.js) before)
